### ISSUE TITLE
除權息歷史紀錄

### ISSUE THREAD

**Issue by frankShih** [FinMind/FinMind#108]
請問一下，

我從 API 得到的數值 (以 2006 年為例)
![image](https://user-images.githubusercontent.com/8334979/112096494-567b0900-8bd9-11eb-87bc-6efba236e487.png)

goodinfo 公開的數值
https://goodinfo.tw/StockInfo/StockDividendSchedule.asp?STOCK_ID=1101

我可以解讀成， API 得到的結果較精準嗎?
還是實際發放時，會像 goodinfo 上所提供之數值一樣，先進行四捨五入?

另外，請問之後有計畫補上 2006 以前的紀錄嗎?

感謝您

**Comment by linsamtw** [comment]
資料來源，公開資訊官測站
[https://mops.twse.com.tw/mops/web/t108sb27](https://mops.twse.com.tw/mops/web/t108sb27)
![image](https://user-images.githubusercontent.com/20013414/112104116-baa3ca00-8be5-11eb-9c7c-a5d8172dd5c4.png)

 2006 以前的資料，我今天晚上補

**Comment by linsamtw** [comment]
已補上 2005-2006 data
