### ISSUE TITLE
Taiwan ETF were not in TaiwanStockStockDividend

### ISSUE THREAD

**Issue by machineCYC** [FinMind/FinMind#12]
Taiwan 股票歷年配息好像沒有 ETF 的資料

**Comment by linsamtw** [comment]
我找找

**Comment by peterdu989** [comment]
請問有空修復嗎? 目前還是沒資料，謝謝

**Comment by linsamtw** [comment]
近期會補上

**Comment by linsamtw** [comment]
ETF 股利 data，資料版型跟原先不太一樣，所以我經過 transpose ，去做轉換
資料來源，https://www.twse.com.tw/zh/ETF/etfDiv

	from FinMind.Data import Load
    import requests
    import pandas as pd
    url = 'http://finmindapi.servebeer.com/api/data'
    list_url = 'http://finmindapi.servebeer.com/api/datalist'
    translate_url = 'http://finmindapi.servebeer.com/api/translation'


    form_data = {'dataset':'StockDividend',
         'stock_id':'0050',
         'date':'2015-01-02',
         }
    res = requests.post(
        url,verify = True,
        data = form_data)

    temp = res.json()
    data = pd.DataFrame( temp['data'] )
    data['date'] = data['date'] + '-' + data['period']
    data = data.drop('period',axis = 1)
    data = Load.transpose(data)
