### ISSUE TITLE
2021/3 月營收 (TaiwanStockMonthRevenue) 資料只有 157 筆

### ISSUE THREAD

**Issue by ccn** [FinMind/FinMind#120]
您好，

透過 TaiwanStockMonthRevenue 查到的2021/3 月營收 (TaiwanStockMonthRevenue) 資料只有 157 筆

似乎沒有更新

謝謝

**Comment by linsamtw** [comment]
![image](https://user-images.githubusercontent.com/20013414/115963900-36ca5e00-a554-11eb-9d92-ed3839880290.png)
你好
資料已經補上囉
