### ISSUE TITLE
請問月營收表 TaiwanStockMonthRevenue的更新時間

### ISSUE THREAD

**Issue by peterdu989** [FinMind/FinMind#123]
請問這張表大約每月幾號會更新，這邊有三月營收了https://mops.twse.com.tw/mops/web/t05st10_ifrs

```R
library(httr)
library(data.table)
library(dplyr)
url = 'https://api.finmindtrade.com/api/v4/data'
response = httr::GET(
    url = url,
    query = list(
        dataset="TaiwanStockMonthRevenue",
        data_id="2330",
        start_date= "2021-01-01",
        token = token # 參考登入，獲取金鑰
    )
)
data = content(response)
df = data$data %>% 
    do.call('rbind',.) %>% 
    data.table
df
```
![image](https://user-images.githubusercontent.com/10435392/116852493-fc815080-ac26-11eb-8a69-34a34b654e57.png)

**Comment by linsamtw** [comment]
大約幾號公布喔
[https://mops.twse.com.tw/nas/t21/sii/t21sc03_110_3_0.html](https://mops.twse.com.tw/nas/t21/sii/t21sc03_110_3_0.html)

我的資料來源是這，我剛剛看，已經有了吧?

**Comment by peterdu989** [comment]
咦，還是這邊是date才是營收月份，我剛跑了一次範例碼還是一樣。
數字看起來也跟網頁的不太一樣 @@

**Comment by linsamtw** [comment]
喔，我知道問題了，我處理一下

peterdu ***@***.***>於 2021年5月6日 週四，下午5:29寫道：

**Comment by linsamtw** [comment]
已修復

![image](https://user-images.githubusercontent.com/20013414/117283098-0bbb0500-ae98-11eb-9fc5-8ad7e5827e37.png)

**Comment by peterdu989** [comment]
感恩~!
