### ISSUE TITLE
請問TaiwanStockFinancialStatements 2020Q4更新了嗎?

### ISSUE THREAD

**Issue by peterdu989** [FinMind/FinMind#126]
2330有Q4, 
2317, 2884只到Q3
應該已經都公布了，再麻煩幫忙看一下，謝謝
```R
library(httr)
library(data.table)
library(dplyr)
url = 'https://api.finmindtrade.com/api/v4/data'
response = httr::GET(
        url = url,
        query = list(
                dataset="TaiwanStockFinancialStatements",
                data_id="2317",
                start_date= "2019-01-02",
                token = token # 參考登入，獲取金鑰
        )
)
data = content(response)
df = data$data %>% 
        do.call('rbind',.) %>% 
        data.table
tail(df)
```
![image](https://user-images.githubusercontent.com/10435392/118491290-69c9d100-b751-11eb-9faf-b976573719c3.png)
![image](https://user-images.githubusercontent.com/10435392/118491009-25d6cc00-b751-11eb-82d0-e76200944dd8.png)
![image](https://user-images.githubusercontent.com/10435392/118491221-5585d400-b751-11eb-95e0-8cad88e96e5a.png)

**Comment by linsamtw** [comment]
資料補上囉，連 Q1 的也有了
