### ISSUE TITLE
調整後股價錯誤

### ISSUE THREAD

**Issue by chris1214git** [FinMind/FinMind#127]
adj_price = dl.taiwan_stock_daily_adj('1220', "2015-01-01", "2020-05-19")
會報錯

**Comment by machineCYC** [comment]
1220 股價資料沒有錯誤，如下連結查詢
https://www.twse.com.tw/zh/page/trading/exchange/STOCK_DAY.html

主要錯誤原因是因為除權息日期(2015-07-10)不是股票交易日

![image](https://user-images.githubusercontent.com/26474547/119213579-cd0d8780-baf2-11eb-901a-32bfb104a232.png)

**Comment by Featasy** [comment]
神奇...原來還有這樣的 除權息日不等於交易日是什麼概念...

**Comment by linsamtw** [comment]
@chris1214git 
新版本 1.4.0 已修復
