### ISSUE TITLE
股東持股分級表

### ISSUE THREAD

**Issue by chris1214git** [FinMind/FinMind#132]
你好:

我照著TaiwanStockInfo裡的stock id去股東持股分級表抓資料
例如:
import requests
import pandas as pd
url = "https://api.finmindtrade.com/api/v4/data"
parameter = {
    "dataset": "TaiwanStockHoldingSharesPer",
    "data_id": stock_id,
    "start_date": "2017-01-01",
    "token": usr_data['token'], # 參考登入，獲取金鑰
}

會發現有幾天的股票數量特別少
![image](https://user-images.githubusercontent.com/37170938/119296059-d92c4d00-bc8a-11eb-8b62-6afb25dc147e.png)

![image](https://user-images.githubusercontent.com/37170938/119296119-ef3a0d80-bc8a-11eb-99cc-179f786914b4.png)

2020-12-11 與 2020-05-08 能抓到的股票數量特別少
且2019-03-29    與 2019-04-03  之間能抓到的股票數量也差異很大
不知道是資料本來就這樣還是API有誤

謝謝

**Comment by linsamtw** [comment]
感謝提醒，已修復，以上幾個日期，都至少有 1600 個 stock
