### ISSUE TITLE
adj price problem

### ISSUE THREAD

**Issue by chris1214git** [FinMind/FinMind#142]
Hi,

我用dataloader取的adj price
發現如果起始位置日期如果太前面，抓到的資料會少很多
應該要能抓到最早一天的股價才對

![image](https://user-images.githubusercontent.com/37170938/119997642-83e19a00-c002-11eb-9dc1-a01b346d7e80.png)

**Comment by linsamtw** [comment]
你好，收到你的訊息了，我們團隊成員 @Featasy 會開始處理

**Comment by Featasy** [comment]
已修復

**Comment by linsamtw** [comment]
`1.4.4` 版本已修復
