### ISSUE TITLE
adj price

### ISSUE THREAD

**Issue by chris1214git** [FinMind/FinMind#153]
![image](https://user-images.githubusercontent.com/37170938/122006776-d0dab400-cde9-11eb-94f4-1434dd12b45b.png)
現在變成取錯股票就會報錯，而不是返回空df(原本的設定)，之前是使用量滿才會報錯
現在要再重寫區分的程式，可以麻煩改回去嗎...

謝謝

**Comment by Featasy** [comment]
Fixed by @machineCYC

**Comment by linsamtw** [comment]
你好，1.4.5 版本已修正
