### ISSUE TITLE
調整後股價

### ISSUE THREAD

**Issue by chris1214git** [FinMind/FinMind#158]
1.4.5的版本
我照著TaiwanStockInfo的stock id來抓調整後股價
但資料筆數有問題
很多日期的股票數變少，像2020-05-05只有60個股票有價格，但那天不是假日
![image](https://user-images.githubusercontent.com/37170938/123360722-5dcafd80-d5a0-11eb-9aaf-e9581a757562.png)

**Comment by linsamtw** [comment]
感謝你的提問，正在請團隊成員 @machineCYC 做檢查

**Comment by linsamtw** [comment]
你好，找到問題了，正在處理中，主要是因為回傳資料，date 型態不一致，明天將會修一版出去

舉例來說，2330，回傳的 date 型態是 Timestamp
![image](https://user-images.githubusercontent.com/20013414/123522563-84984980-d6f0-11eb-8ea4-bed7ca74a3e6.png)

而另一檔股票，3051，date 資料型態是 str，
![image](https://user-images.githubusercontent.com/20013414/123522583-a5609f00-d6f0-11eb-8984-5f1d832390df.png)

所以當兩個資料合併後，再做 groupby，就會造成這個問題
![image](https://user-images.githubusercontent.com/20013414/123522598-c6c18b00-d6f0-11eb-977b-acf6ae571009.png)

新版本會修正此問題

**Comment by chris1214git** [comment]
了解 感謝!

**Comment by linsamtw** [comment]
`1.4.6` 版本已修正此問題
