### ISSUE TITLE
加權股價報酬指數

### ISSUE THREAD

**Issue by tktw9527** [FinMind/FinMind#168]
https://www.twse.com.tw/zh/page/trading/indices/MFI94U.html

https://www.tpex.org.tw/web/stock/iNdex_info/reward_index/ROE.php?l=zh-tw

**Comment by linsamtw** [comment]
TaiwanStockTotalReturnIndex

**Comment by linsamtw** [comment]
https://finmind.github.io/tutor/TaiwanMarket/Technical/#taiwanstocktotalreturnindex
