### ISSUE TITLE
能有一次抓當日多筆即時股價的功能?

### ISSUE THREAD

**Issue by obxyann** [FinMind/FinMind#177]
可以考慮類似 TaiwanStockTickSnapshot  但不需要全部股票(可指定多筆), 只是除最後成交價, 還有當日的 ohlcv
(or TaiwanStockPrice ??)
這樣方便即時監視自選的股價K棒(報價看板)變化, 目前似乎看不到有這個功能, 如果要做到需要頻繁叫用查詢單一股票...?

```
輸入 stock ids
"data_id": "2330,1001,2002,3003"

   date (deal_date)     stock_id  deal_price  volume  open  high  low   prev_closed  accum_volume
1  2020-01-02 09:10:20  2330      333.5       3       300   350   299   299.5        1234
2  2020-01-02 09:10:21  1001      10.5        13      8.2   12    8.1   16.5         67812
3  2020-01-02 09:20:23  2002      20.5        23      11    25    20    20           1261
4  2020-01-02 09:10:20  3003      30.5        13      28    22    11.5  28.1         8099
```

**Comment by linsamtw** [comment]
> 可以考慮類似 TaiwanStockTickSnapshot 但不需要全部股票, 只是除最後成交價, 還有當日的 ohlcv
> (or TaiwanStockPrice ??)
> 這樣方便即時監視自選的股價K棒(報價看板)變化, 目前似乎看不到有這個功能, 如果要做到需要頻繁叫用查詢單一股票...?
> 
> ```
> 輸入 stock ids
> "data_id": "2330,1001,2002,3003"
> 
>     date (deal_date)              stock_id   deal_price  volume  open high low    prev_closed accum_volume
> 1  2020-01-02 09:10:20     2330       333.5        3            300   350  299   299.5          1234
> 2  2020-01-02 09:10:21     1001       10.5         13           8       12    8       16.5            67812
> 3  2020-01-02 09:20:23     2002       20.5         23          11      25    20      20              1261
> 4  2020-01-02 09:10:20     3003       30.5         13          28      22    11.5   28.1            8099
> ```

**Comment by linsamtw** [comment]
import requests
    import pandas as pd
    url = "https://api.finmindtrade.com/api/v4/taiwan_stock_tick_snapshot"
    parameter = {
        "data_id": "2330",
        "token": "", # 參考登入，獲取金鑰
    }
    resp = requests.get(url, params=parameter)
    data = resp.json()
    data = pd.DataFrame(data["data"])
    print(data.head())

如果不帶 data_id 參數，會一次回傳約 2000 檔股票當下的即時報價
