### ISSUE TITLE
1558 TaiwanStockFinancialStatements 缺部分資料

### ISSUE THREAD

**Issue by peterdu989** [FinMind/FinMind#179]
**Describe the bug (please complete the following information)**[清晰簡潔的描述 bug]
1558 TaiwanStockFinancialStatements 缺部分資料

**To Reproduce (please complete the following information)**[一步一步說明如何重現 bug]
```R
url = 'https://api.finmindtrade.com/api/v4/data'
response = httr::GET(
        url = url,
        query = list(
                dataset="TaiwanStockFinancialStatements",
                data_id="1558",
                start_date= "2010-01-01",
                token = token # 參考登入，獲取金鑰
        )
)
data = content(response)
df = data$data %>% 
        do.call('rbind',.) %>% 
        data.table
unique(unlist(df$date))
```

**Expected behavior (please complete the following information)**[清晰簡潔的描述你預期的結果]
2018Q4, 2019全年有資料

**Screenshots**[如果方便的話，利用截圖來協助說明你的問題]
![image](https://user-images.githubusercontent.com/10435392/126861906-8f11aad3-96c1-46e6-94c8-032768c9650a.png)

**Desktop (please complete the following information):**[提供程式的執行環境]
 - OS: windows
 - R open 4.0.2

再麻煩查看，謝謝!!

**Comment by linsamtw** [comment]
已修正
