### ISSUE TITLE
股價錯誤

### ISSUE THREAD

**Issue by ji3g4m6zo6** [FinMind/FinMind#182]
**Describe the bug (please complete the following information)**

個股報價錯誤

**To Reproduce (please complete the following information)**

以 2408 南亞科為例
2014-01-10 的股價在 56 元左右
透過以下程式得到的 2014-01-10  股價在 6 元上下
```
dl.taiwan_stock_daily(stock_id='2408', start_date='2014-01-01', end_date='2015-01-01')
```

**Expected behavior (please complete the following information)**

價格應與實際價格相同

**Screenshots**

Google 查詢的股價：
![正確股價](https://i.imgur.com/RJ4tUJJ.png)

套件回傳的股價：
![程式股價](https://i.imgur.com/1orRtnM.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser Chrome
 - Python Version 3.6.9
 - FinMind package Version 1.4.9

**Additional context**

查看歷史資料發現 
南亞科在 2014-08-26 減資
不知是否因此造成價格有出入

![減資](https://imgur.com/wLFNyuO.png)

**Comment by linsamtw** [comment]
![image](https://user-images.githubusercontent.com/20013414/128959562-9562de8e-d613-4e03-a9b2-b29b3febf152.png)

資料來源，證交所
https://www.twse.com.tw/zh/page/trading/exchange/MI_INDEX.html

證交所上面的數字，確實是 6 元上下喔

**Comment by ji3g4m6zo6** [comment]
已去信證交所網站詢問相關資料的問題
若收到回覆會再留言回報
