### ISSUE TITLE
新增台股發行股數？

### ISSUE THREAD

**Issue by hgdfmjg2715** [FinMind/FinMind#184]
**Is your feature request related to a problem? Please describe.**[清晰簡潔的描述你遇到的問題]
我想判斷個股票的股本，藉此來判斷一間公司的大小，經查詢基本就是看發行股數，故想詢問是否可以加入到TaiwanStockInfo內

**Describe the solution you'd like**[清晰簡潔的描述你希望提供的結果]
在TaiwanStockInfo新增發行股數欄位

**Describe alternatives you've considered**[清晰簡潔的描述你曾經想過的替代方案]
這應該有點難替代，就是單純的資料
不然就是我自己扒網抓了...

**Additional context**[額外的資訊幫助釐清問題]
我看證交所是有提供這類資料的

**Comment by linsamtw** [comment]
建議參考 https://finmind.github.io/tutor/TaiwanMarket/Chip/#taiwanstockshareholding

如果要作分析，需要看歷史發行股數，看當下不準，所以比較建議的做法是，
去拿 `外資持股表 TaiwanStockShareholding` 的資料，會比較好

![image](https://user-images.githubusercontent.com/20013414/132957140-7d8b5234-911a-4e63-a122-659880ec227d.png)
