### ISSUE TITLE
這些股票沒有當日tick成交資料

### ISSUE THREAD

**Issue by manateechen** [FinMind/FinMind#194]
確定當日有交易，但是沒tick資料
9103 2021-04-15
3257 2021-04-26
3294 2021-04-28
3526 2021-05-03
4977 2021-05-04
6712 2021-05-04
8027 2021-05-04
9105 2021-05-04
6712 2021-05-11
9103 2021-05-11
3081 2021-05-12
5522 2021-05-12
6492 2021-05-12
9940 2021-05-12
3005 2021-05-17
4152 2021-05-19
6438 2021-06-01
9105 2021-06-03
6669 2021-06-11
3092 2021-06-16
9105 2021-06-22
9103 2021-06-25
6409 2021-06-28
6438 2021-07-05
9105 2021-07-06
6525 2021-07-12
3580 2021-07-13
5478 2021-07-16
2032 2021-07-19
6143 2021-07-19
9105 2021-07-29
9103 2021-08-16
9103 2021-08-25
9103 2021-09-06
9103 2021-09-30

**Comment by linsamtw** [comment]
done, please checking that
