### ISSUE TITLE
cors problem

### ISSUE THREAD

**Issue by y2468101216** [FinMind/FinMind#20]
跨網域請求會失敗，因為 options method 回傳 405

**Comment by linsamtw** [comment]
> 跨網域請求會失敗，因為 options method 回傳 405

你是用 ajax 發 post 嗎?

可以給我看看 code? 我測試看看

**Comment by y2468101216** [comment]
http://jsfiddle.net/1mvw2qc9/

**Comment by linsamtw** [comment]
> http://jsfiddle.net/1mvw2qc9/
> 
> 我現在是繞過去了，但是這樣做起來還是不方便

好，我解解看

**Comment by linsamtw** [comment]
你試試看現在，能不能成功，我剛剛用你提供的 code run，是成功的

**Comment by y2468101216** [comment]
我試過了，可以了，感謝
