### ISSUE TITLE
請問API能否支援TaiwanStockPriceAdj資料集

### ISSUE THREAD

**Issue by shinylin** [FinMind/FinMind#203]
**Is your feature request related to a problem? Please describe.**[清晰簡潔的描述你遇到的問題]
TaiwanStockPriceAdj資料集目前無法透過API取得，會回應不在列舉裡
但是透過python範例程式是可以正常取得的，看了python原始碼是自行換算的

**Describe the solution you'd like**[清晰簡潔的描述你希望提供的結果]
希望列舉加入支援TaiwanStockPriceAdj資料集

**Describe alternatives you've considered**[清晰簡潔的描述你曾經想過的替代方案]
無

**Additional context**[額外的資訊幫助釐清問題]
無

**Comment by linsamtw** [comment]
好，會加入開發時程中

**Comment by dream4magi** [comment]
有相同需求，感謝!

**Comment by linsamtw** [comment]
已完成開發

https://finmind.github.io/tutor/TaiwanMarket/Technical/#taiwanstockpriceadj
