### ISSUE TITLE
Import 時的警告訊息 (dtype)

### ISSUE THREAD

**Issue by xareelee** [FinMind/FinMind#204]
**Describe the bug (please complete the following information)**[清晰簡潔的描述 bug]

Python 3.10 在 `import FinMind` 時，發出兩則警告訊息:

```
.venv/lib/python3.10/site-packages/FinMind/strategies/base.py:423: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  def final_stats(self) -> pd.Series():

.venv/lib/python3.10/site-packages/FinMind/strategies/base.py:450: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  def compare_market_stats(self) -> pd.Series():
```

**Desktop (please complete the following information):**[提供程式的執行環境]
 - OS: macOS 12.3.1
 - Python Version: 3.10.3
 - FinMind package Version: 1.5.5

**Comment by linsamtw** [comment]
這是 python 3.10 問題，我們當初開發，沒有測過 3.10 的狀況，以下 3.6, 3.7

![image](https://user-images.githubusercontent.com/20013414/171783125-3f33d47f-11cf-4722-8e49-91ec3fdceb49.png)

![image](https://user-images.githubusercontent.com/20013414/171784669-9fdbbdbb-8336-4211-934d-a7dee1643126.png)

**Comment by linsamtw** [comment]
![image](https://user-images.githubusercontent.com/20013414/174466146-4a5d226e-3048-4aa2-84e9-4acb39d1fa52.png)
麻煩幫我更新版本，1.5.6，已解這問題
