### ISSUE TITLE
taiwan_stock_daily 含有查不到資料的股票代號

### ISSUE THREAD

**Issue by xareelee** [FinMind/FinMind#205]
**Describe the bug (please complete the following information)**[清晰簡潔的描述 bug]

FinMind API `taiwan_stock_daily` 回傳列表內含有一個上市代號「1230 聯成食」，但是找不到這筆股票資訊。

industry_category | stock_id | stock_name | type | date
-- | -- | -- | -- | --
電器電纜 | 1230 | 聯成食 | twse | 2022-04-27

**Comment by linsamtw** [comment]
那可能就是真的沒有
因為我去 yahoo 股市也找不到
![image](https://user-images.githubusercontent.com/20013414/171589450-278b2b6a-39e9-4b9b-80c2-88838e675b03.png)
