### ISSUE TITLE
個股發行張數需求

### ISSUE THREAD

**Issue by LightTsao** [FinMind/FinMind#206]
**Is your feature request related to a problem? Please describe.**[清晰簡潔的描述你遇到的問題]
我需要個股發行張數的資料
經過確認沒有目前沒有dataset有相關資料
謝謝

**Describe the solution you'd like**[清晰簡潔的描述你希望提供的結果]
無

**Describe alternatives you've considered**[清晰簡潔的描述你曾經想過的替代方案]
無

**Additional context**[額外的資訊幫助釐清問題]
無

**Comment by machineCYC** [comment]
請問知道哪邊有相關的資料嗎?

**Comment by linsamtw** [comment]
請問發行股數，符合你的需求嗎?

![image](https://user-images.githubusercontent.com/20013414/224548701-f5977391-07c7-416a-aa6e-044d17eb9591.png)
