### ISSUE TITLE
盤中即時股價，可多選股票 (download全部股票時間消耗太久)

### ISSUE THREAD

**Issue by dinoi22g** [FinMind/FinMind#208]
盤中即時股價，可多選股票 (透過傳入list來取得多個指定股價資訊) 。 獲取全部股票的下載耗時過長

**Comment by linsamtw** [comment]
![image](https://user-images.githubusercontent.com/20013414/174474422-d18534ec-7009-42c5-a1cd-d394e5249ca2.png)

**Comment by linsamtw** [comment]
https://finmind.github.io/tutor/TaiwanMarket/Technical/#taiwan_stock_tick_snapshot-backersponsor
