### ISSUE TITLE
關於三大法人與融資融券

### ISSUE THREAD

**Issue by litonchen** [FinMind/FinMind#216]
1.請問最晚數據會更新
2.是所有的股票一次全部更新?還是分批更新?

**Comment by linsamtw** [comment]
> 1.請問最晚數據會更新 

最晚晚上 9.30 以前會更新所有數據

> 2.是所有的股票一次全部更新?還是分批更新?

分批，例如上市股票跟上櫃股票，因為是不同交易所，所以更新時間並沒有統一
