### ISSUE TITLE
About output from TaiwanStockInfo dataset

### ISSUE THREAD

**Issue by obxyann** [FinMind/FinMind#218]
Although this is not a bug but
1. below category name has redundant space at end of string
        "industry_category": "所有證券 "
2. if 'Warrants' can't be completed/updated, it should not include in the output.
3. can't understand the 'date' field meaning
        "date": "2022-07-09"
    I think it should better be the 'first marketing date' as  [TWSE ](https://isin.twse.com.tw/isin/C_public.jsp?strMode=2)

**Comment by linsamtw** [comment]
> below category name has redundant space at end of string
> "industry_category": "所有證券 "

fixed

> if 'Warrants' can't be completed/updated, it should not include in the output.

這什麼意思?

> can't understand the 'date' field meaning
> "date": "2022-07-09"
> I think it should better be the 'first marketing date' as [TWSE](https://isin.twse.com.tw/isin/C_public.jsp?strMode=2)

更新時間

**Comment by obxyann** [comment]
權證部分似乎不完整也沒及時更新，是否還有列出的必要?

**Comment by linsamtw** [comment]
![image](https://user-images.githubusercontent.com/20013414/178490228-234300a2-7231-42bf-8c64-80befe911727.png)

近期有 user 詢問權證相關 data，我們已開發完成，最近會寫到文件上

**Comment by linsamtw** [comment]
由於權證資料量過大，為了避免影響現有 user 使用，因此開新的 dataset

**Comment by obxyann** [comment]
了解~TaiwanStockInfo  舊的權證資料以後會刪除對吧 ...謝謝~
