### ISSUE TITLE
特定股票查詢月營收資料有缺少月份

### ISSUE THREAD

**Issue by obxyann** [FinMind/FinMind#219]
資料集 dataset=TaiwanStockMonthRevenue
股號 data_id=4572
起始日期 start_date=2019-01-01

結果  2019-01  ~ 2019-06 都沒有任何資料, 只回傳 2018-12, 2019-07,  2019-08,.....
查 goodinfo.tw 網站，該期間都有資料

**Comment by linsamtw** [comment]
![image](https://user-images.githubusercontent.com/20013414/182761445-e89ee132-8fe7-4e90-8511-e62e2346c810.png)

fixed
