### ISSUE TITLE
API rate limit

### ISSUE THREAD

**Issue by CoyoteLeo** [FinMind/FinMind#227]
根據 FinMind User Page 的用量顯示我的 API 用量尚未頂到上限，但是實際使用 API 卻遇到
`requests.exceptions.HTTPError: 402 Client Error: Payment Required for url: https://api.finmindtrade.com/api/v4/data?dataset=TaiwanStockPrice&data_id=8171&start_date=2022-09-01&end_date=2022-09-11&token=<token>`

借用朋友 token 也一樣會遇到這個問題，想問幾個問題
- Rate limit 是根據什麼限制的
  - By token?
  - By IP?
- Rate limit 是不是除了一小時內的呼叫量之外是不是還有更小顆粒度的限制(req/min or req/sec)?

**Comment by linsamtw** [comment]
你的程式碼借我看看

**Comment by linsamtw** [comment]
幫我寄信到官方信箱
finmind.tw@gmail.com
