### ISSUE TITLE
一次拿特定日期，所有資料無法回傳資料 (當日沖銷交易標的及成交量值 & 股價日成交資訊)

### ISSUE THREAD

**Issue by HsiWeiii** [FinMind/FinMind#228]
先前可以直接針對某一天拿出所有股票的資料, 現在必須要強制加上 data_id 才能抓到資料, 不知道是否在某次更新後動到了原始的程式碼, 謝謝！

![image](https://user-images.githubusercontent.com/93362853/193595104-464b5840-330c-4dec-8638-4044c6040b42.png)

**Comment by linsamtw** [comment]
![image](https://user-images.githubusercontent.com/20013414/193604368-2f6dcaae-2036-4cd0-808b-52bdfb548326.png)
應該是你 token 過期囉

**Comment by HsiWeiii** [comment]
沒錯！不好意思沒注意到, 已經重新訂閱, 謝謝！

lin sam ***@***.***> 於 2022年10月3日 週一 晚上10:36寫道：
