### ISSUE TITLE
新增台股分K資料

### ISSUE THREAD

**Issue by linsamtw** [FinMind/FinMind#233]
**Is your feature request related to a problem? Please describe.**[清晰簡潔的描述你遇到的問題]

https://www.facebook.com/groups/401634838071226/permalink/682772129957494/

**Describe the solution you'd like**[清晰簡潔的描述你希望提供的結果]

**Describe alternatives you've considered**[清晰簡潔的描述你曾經想過的替代方案]

**Additional context**[額外的資訊幫助釐清問題]

**Comment by machineCYC** [comment]
增加10年線

**Comment by linsamtw** [comment]
- 新增台股、期貨分K

**Comment by linsamtw** [comment]
台股
- 1 分 K
- 10 年均線
期貨
- 1 分 K

**Comment by superdavid0816** [comment]
您好，請問新增的1分K的api是哪一個，我在
https://api.finmindtrade.com/docs#/default/data_api_v4_data_get
不知道要使用哪一個才是正確的1分K的api
請您指點一下。
謝謝

**Comment by machineCYC** [comment]
目前還沒完成喔! 有任何新的消息會在這更新! 謝謝

**Comment by linsamtw** [comment]
已完成[分 K](https://finmind.github.io/tutor/TaiwanMarket/Technical/#k-taiwanstockkbar-sponsor) 與 [10 年線
](https://finmind.github.io/tutor/TaiwanMarket/Technical/#taiwanstock10year-backersponsor)

cc @superdavid0816
