### ISSUE TITLE
'API 使用次數' Request Method should be GET

### ISSUE THREAD

**Issue by jason19970210** [FinMind/FinMind#236]
As mentioned in the subject, 

the documentation for the API Usage Information page says use `POST` with the payload contains token,
but in fact, the API server will return successful with `GET` method.

Please take a look and fix the documentation.
Thanks a lot !

ref: https://finmind.github.io/api_usage_count/#token-api

**Comment by machineCYC** [comment]
Hi @jason19970210 ,

thanks for this reminder, we will modify the document

**Comment by machineCYC** [comment]
document is updated, thanks
