### ISSUE TITLE
在 Anaconda 虛擬環境下，plotting 有 error 

### ISSUE THREAD

**Issue by Wrrk** [FinMind/FinMind#237]
**Describe the bug (please complete the following information)**[清晰簡潔的描述 bug]
在 Anaconda 虛擬環境下，plotting 有 error 。

**To Reproduce (please complete the following information)**[一步一步說明如何重現 bug]

```
Anaconda 虛擬環境建立
開啟 Anaconda Prompt
1. conda create -n finm_test python=3.7.4

2. conda activate finm_test

3. conda install spyder

4. pip install FinMind
```
python 程式
```
# 取得股價
from FinMind.data import DataLoader

dl = DataLoader()
# 下載台股股價資料
stock_data = dl.taiwan_stock_daily(
    stock_id='2609', start_date='2018-01-01', end_date='2021-06-26'
)
# 下載三大法人資料
stock_data = dl.feature.add_kline_institutional_investors(
    stock_data
) 
# 下載融資券資料
stock_data = dl.feature.add_kline_margin_purchase_short_sale(
    stock_data
)

# 繪製k線圖
from FinMind import plotting

plotting.kline(stock_data)
```
**Expected behavior (please complete the following information)**[清晰簡潔的描述你預期的結果]
正常顯示 plotting 畫圖的結果

**Screenshots**[如果方便的話，利用截圖來協助說明你的問題]
錯誤訊息
![image](https://user-images.githubusercontent.com/46361472/216825800-24256947-4e84-4f96-81b0-908d39dcdd25.png)

**Desktop (please complete the following information):**[提供程式的執行環境]
 - OS: windows
 - Python Version 3.7.4
 - FinMind package Version 1.5.9
 - conda: 4.10.3

**Additional context**[額外的資訊幫助釐清問題]

**Comment by machineCYC** [comment]
可以先使用 python 3.6.9! 剛測試是沒有問題

**Comment by Wrrk** [comment]
我改用 python 3.6.9 仍然有相同錯誤，不知道會不會跟 conda 版本有關，我這邊補充一下 conda 版本: 4.10.3

**Comment by Asthma0106** [comment]
我也有一樣的問題,  

> **Describe the bug (please complete the following information)**[清晰簡潔的描述 bug] 在 Anaconda 虛擬環境下，plotting 有 error 。
> 
> **To Reproduce (please complete the following information)**[一步一步說明如何重現 bug] Steps to reproduce the behavior:
> 
> ```
> Anaconda 虛擬環境建立
> 開啟 Anaconda Prompt
> 1. conda create -n finm_test python=3.7.4
> 
> 2. conda activate finm_test
> 
> 3. conda install spyder
> 
> 4. pip install FinMind
> ```
> 
> python 程式
> 
> ```
> # 取得股價
> from FinMind.data import DataLoader
> 
> dl = DataLoader()
> # 下載台股股價資料
> stock_data = dl.taiwan_stock_daily(
>     stock_id='2609', start_date='2018-01-01', end_date='2021-06-26'
> )
> # 下載三大法人資料
> stock_data = dl.feature.add_kline_institutional_investors(
>     stock_data
> ) 
> # 下載融資券資料
> stock_data = dl.feature.add_kline_margin_purchase_short_sale(
>     stock_data
> )
> 
> # 繪製k線圖
> from FinMind import plotting
> 
> plotting.kline(stock_data)
> ```
> 
> **Expected behavior (please complete the following information)**[清晰簡潔的描述你預期的結果] 正常顯示 plotting 畫圖的結果
> 
> **Screenshots**[如果方便的話，利用截圖來協助說明你的問題] 錯誤訊息 ![image](https://user-images.githubusercontent.com/46361472/216825800-24256947-4e84-4f96-81b0-908d39dcdd25.png)
> 
> **Desktop (please complete the following information):**[提供程式的執行環境]
> 
> * OS: windows
> * Python Version 3.7.4
> * FinMind package Version 1.5.9
> * conda: 4.10.3
> 
> **Additional context**[額外的資訊幫助釐清問題] Add any other context about the problem here.

我也有相同的問題, 我的環境也是一樣的

**Comment by linsamtw** [comment]
https://colab.research.google.com/drive/1u1cJGFNCLOeBIR0PdeKlsqgKBJSvJg_y?usp=sharing

你好，在 colab 環境上，是可以成功運作的，
建議參考 colab 的環境去實作
