### ISSUE TITLE
20230203 期貨缺少夜盤資料

### ISSUE THREAD

**Issue by arthur55** [FinMind/FinMind#238]
**Describe the bug (please complete the following information)**[清晰簡潔的描述 bug]
20230203 期貨缺少夜盤資料

**To Reproduce (please complete the following information)**[一步一步說明如何重現 bug]
```python
import requests
import pandas as pd
url = "https://api.finmindtrade.com/api/v4/data"
parameter = {
    "dataset": "TaiwanFuturesDaily",
    "data_id":"TX",
    "start_date": "2023-02-03",
    "token": "{MY_TOKEN}", # 參考登入，獲取金鑰
}
data = requests.get(url, params=parameter)
data = data.json()
data = pd.DataFrame(data['data'])
data
```

**Expected behavior (please complete the following information)**[清晰簡潔的描述你預期的結果]
當天應有夜盤資料

**Screenshots**[如果方便的話，利用截圖來協助說明你的問題]
![image](https://user-images.githubusercontent.com/8954015/217044189-df1a6d95-48ff-402c-8040-87d4fb659f6c.png)

**Desktop (please complete the following information):**[提供程式的執行環境]
 - OS: Ubuntu 20
 - Browser: Edge
 - Python Version: 3.8
 - FinMind package Version: 1.5.0

**Additional context**[額外的資訊幫助釐清問題]

**Comment by linsamtw** [comment]
資料已修復，感謝

**Comment by arthur55** [comment]
@linsamtw 因為應該是同樣的問題，我就直接聽在這了，2023-02-09 缺少日盤資料，謝謝
![image](https://user-images.githubusercontent.com/8954015/217883747-18aa83c8-99d1-4ce6-8abb-cd5fd7a2f661.png)
