### ISSUE TITLE
新增台股可轉債交易資訊

### ISSUE THREAD

**Issue by mysk8** [FinMind/FinMind#246]
**[清晰簡潔的描述你遇到的問題]**
希望可以新增可轉債(CB)的交易資訊

**[清晰簡潔的描述你希望提供的結果]**
可轉債為公司發行的債券，代號共五碼，前四碼為公司股票代號，最後一碼為發債版本，例如: 26034長榮四
目前市面上的看盤軟體都可以找到可轉債的收盤價，但無法看到逐筆的交易資訊，
希望能新增逐筆的資訊，包含
-成交日期
-成交時間
-逐筆成交張數
-成交價

**[額外的資訊幫助釐清問題]**
可參考櫃買中心的資料，但這個似乎也查不到逐筆的資訊
https://www.tpex.org.tw/web/bond/bonds_info/cbq/NewCB_day_qry.php?l=zh-tw

**Comment by machineCYC** [comment]
可能需要有逐筆的資料源喔，如果有在跟我們分享! 謝謝

**Comment by ChangSian** [comment]
可轉債目前應該是沒有逐筆資料，但建議可以新增以下資料
日成交資料：https://www.tpex.org.tw/web/bond/tradeinfo/cb/CBDaily.php?l=zh-tw
三大法人日交易資訊 : https://www.tpex.org.tw/web/bond/bonds_info/daily_trade/NewCb3itrade.php?l=zh-tw
停止轉換資訊：https://www.tpex.org.tw/web/bond/tradeinfo/cb/CBSuspend.php?l=zh-tw
可轉債發行資料：https://www.tpex.org.tw/web/bond/publish/convertible_bond_search/memo.php?l=zh-tw

**Comment by linsamtw** [comment]
近期會安排人力，收集相關資料

**Comment by linsamtw** [comment]
https://finmind.github.io/tutor/TaiwanMarket/ConvertibleBond/
已新增
