### ISSUE TITLE
查詢目前api使用次數

### ISSUE THREAD

**Issue by manateechen** [FinMind/FinMind#247]
目前只能在網頁上查詢自己的 api 已使用次數
我怕使用次數超過 一直查看網頁

是否可以提供python api 查詢
返回目前api 已使用次數
好讓我快到達上限的時候暫停一下

**Comment by seanmars** [comment]
> 目前只能在網頁上查詢自己的 api 已使用次數 我怕使用次數超過 一直查看網頁
> 
> 是否可以提供python api 查詢 返回目前api 已使用次數 好讓我快到達上限的時候暫停一下

已經有這個 API，請參考官方 API 說明 -> https://finmind.github.io/api_usage_count/
