### ISSUE TITLE
Wrong TaiwanFuturesInstitutionalInvestors data on 2022-10-01

### ISSUE THREAD

**Issue by arthur55** [FinMind/FinMind#248]
**Describe the bug (please complete the following information)**[清晰簡潔的描述 bug]
Wrong TaiwanFuturesInstitutionalInvestors data on 2022-10-01

**To Reproduce (please complete the following information)**[一步一步說明如何重現 bug]
```python
import requests
import pandas as pd
url = "https://api.finmindtrade.com/api/v4/data"
parameter = {
    "dataset": "TaiwanFuturesInstitutionalInvestors",
    "data_id": "TX",# "TXO"
    "start_date": "2022-10-01",
    "end_date": "2022-10-01",
    "token": "", # 參考登入，獲取金鑰
}
resp = requests.get(url, params=parameter)
data = resp.json()
df = pd.DataFrame(data["data"])
print(df.head())
```

**Expected behavior (please complete the following information)**[清晰簡潔的描述你預期的結果]
It should not return any data on "2022-10-01".

**Screenshots**[如果方便的話，利用截圖來協助說明你的問題]
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/8954015/229769133-6da4b4ea-2bfa-42c3-bc1e-514781708e6c.png">
<img width="918" alt="image" src="https://user-images.githubusercontent.com/8954015/229768772-af8440f7-7c5b-4c55-b6e6-09e978ea4650.png">

**Comment by linsamtw** [comment]
處理中

**Comment by linsamtw** [comment]
已修正
![image](https://user-images.githubusercontent.com/20013414/230283837-bb1965e5-9bb5-4a7a-8277-304983b20c3f.png)
