### ISSUE TITLE
Can't fetch complete TPEX data.

### ISSUE THREAD

**Issue by hvgmbdmg** [FinMind/FinMind#25]
Here is a simple code to load TPEX data.
```
from FinMind.Data import Load
Load.FinData(dataset = 'TaiwanStockPrice', select = '1240', date = '2020-1-1')
```
The return does not contain 3/4, 3/5, 3/10, 3/12 data.
By the way, I do not check all the dates.

Finally, TWSE stock works pretty well.
```
from FinMind.Data import Load
Load.FinData(dataset = 'TaiwanStockPrice', select = '1101', date = '2020-1-1')
```

**Comment by linsamtw** [comment]
感謝，已修復

**Comment by hvgmbdmg** [comment]
Hey @linsamtw 

Very quick and nice job.
But, I still find some missing data.
Ex. 5102, 7402, 9949 does not contain 3/2 data.

Maybe you need to update 3/2 data too.
Thanks a lot.

**Comment by linsamtw** [comment]
已修復
