### ISSUE TITLE
三大法人買賣資料似乎有問題?

### ISSUE THREAD

**Issue by YI-CHENG-SHIH645** [FinMind/FinMind#27]
您好
三大法人買賣的資料好像怪怪的
![image](https://user-images.githubusercontent.com/53689821/78220769-b8d48880-74f4-11ea-9ed0-63df2762e9ee.png)
查了一下 2020/04/01 4736 外資/投信/自營商 分別是 -119/39/19
只有外資 78-197是正確的

**Comment by linsamtw** [comment]
ok，感謝，修復中

**Comment by linsamtw** [comment]
已修復
