### ISSUE TITLE
在 BackTest 的 simulate() 方法中 trade_detail['hold_volume'] 不應該有小數部分

### ISSUE THREAD

**Issue by sakkyoi** [FinMind/FinMind#273]
**Describe the bug (please complete the following information)**[清晰簡潔的描述 bug]
當執行完 BackTest 的 simulate() 後，呼叫 BackTest.trade_detail 會報錯：
```
ValidationError: 1 validation error for TradeDetail
hold_volume
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=5189.385145, input_type=float]
    For further information visit https://errors.pydantic.dev/2.4/v/int_from_float
```

**To Reproduce (please complete the following information)**[一步一步說明如何重現 bug]
1. 建立一個 backtest_obj，stock_id 為 2884，期間為2023/01/30~2023/10/31
2. backtest_obj.add_strategy(ContinueHolding) 然後執行 backtest_obj.simulate()
3. print(backtest_obj.trade_detail)
4. 錯誤就會產生

**Expected behavior (please complete the following information)**[清晰簡潔的描述你預期的結果]
應該要能正常 print 出 backtest_obj.trade_detail

**Screenshots**[如果方便的話，利用截圖來協助說明你的問題]
None

**Desktop (please complete the following information):**[提供程式的執行環境]
 - OS: Windows
 - Python Version 3.10
 - FinMind package Version 1.6.3

**Additional context**[額外的資訊幫助釐清問題]
首先，這個問題如果用 backtest_obj._trade_detail 即可解決，但我認為這是一個不應存在的 bug，因此回報問題。
問題的產生是由於個股資料中，StockEarningsDistribution 欄位可能是一個小數數值。
```python
# in strategies/base.py line 318
def __compute_div_income(trader, cash_div: float, stock_div: float):
    gain_stock_div = stock_div * trader.hold_volume / 10  # 此處 stock_div 為 stock_price 中 StockEarningsDistribution 欄位，可能存在小數
    gain_cash = cash_div * trader.hold_volume
    origin_cost = trader.hold_cost * trader.hold_volume
    trader.hold_volume += gain_stock_div  # 此處直接將 gain_stock_div 加入，導致持有量出現小數部分
```
股票股利畸零股應被直接換算成現金，因此這個值是否要變成整數部分加入 hold_volume，小數部分加入 Profit (實務上還會被扣匯費)

**Comment by linsamtw** [comment]
@machineCYC 有空時幫看

**Comment by linsamtw** [comment]
@sakkyoi 
我在 colab 執行，是正常的耶，能提供更多資訊嗎?
![image](https://github.com/FinMind/FinMind/assets/20013414/a7fc3eef-543f-4ba2-b9fb-bdc0b6bfd83e)

**Comment by sakkyoi** [comment]
@linsamtw 
抱歉回晚了，我用 colab 也執行了相同的程式碼，問題是可以再現的，以下是我的執行結果：
![image](https://github.com/FinMind/FinMind/assets/22865542/45b1582c-774d-4cb3-99ad-535346d69a37)

**Comment by linsamtw** [comment]
已 release to 1.6.6 version
