### ISSUE TITLE
Trading_Volume單位不一致

### ISSUE THREAD

**Issue by YI-CHENG-SHIH645** [FinMind/FinMind#28]
您好
4171的成交量單位不一致
![image](https://user-images.githubusercontent.com/53689821/78222514-f850a400-74f7-11ea-9b5b-44faaec08421.png)
前陣子是張 後來突然改用股(後面多3個0) 連帶影響Trading_money

**Comment by linsamtw** [comment]
感謝，最近會重新執行爬蟲，將資料更新

**Comment by linsamtw** [comment]
已修復
