### ISSUE TITLE
權證分點沒資料

### ISSUE THREAD

**Issue by wezzyzzs** [FinMind/FinMind#283]
![image](https://github.com/FinMind/FinMind/assets/86904909/06ec51d9-3b9c-405f-8696-f3cfd94d801e)

在12/26 時撈12/25的權證分點沒資料

我有撈兩檔 一檔是中砂 (1560) 一檔是智通 (8932)

中沙第一次跑的時候沒有 重啟jupyter 之後就撈的到 但是智通不論有無重啟都沒有資料
也查看過無超過API 使用次數

**Comment by linsamtw** [comment]
你怎麼撈的?

> 我有撈兩檔 一檔是中砂 (1560) 一檔是智通 (8932)

這兩檔不是權證
