### ISSUE TITLE
5871沒有月營收

### ISSUE THREAD

**Issue by YI-CHENG-SHIH645** [FinMind/FinMind#29]
您好
![image](https://user-images.githubusercontent.com/53689821/78225449-d1e13780-74fc-11ea-9996-f2170ddfe8a1.png)
5871查不到月營收

**Comment by machineCYC** [comment]
修復中。感謝

**Comment by linsamtw** [comment]
有資料囉

**Comment by YI-CHENG-SHIH645** [comment]
謝謝!!
