### ISSUE TITLE
除權除息結果表 TaiwanStockDividendResult

### ISSUE THREAD

**Issue by abcd334** [FinMind/FinMind#299]
**Describe the bug (please complete the following information)**[清晰簡潔的描述 bug]
資料有誤
![image](https://github.com/FinMind/FinMind/assets/123975061/9c783c40-f4e7-44f6-b164-10773ca57bcb)

**To Reproduce (please complete the following information)**[一步一步說明如何重現 bug]
`url = "https://api.finmindtrade.com/api/v4/data"
parameter = {
    "dataset": "TaiwanStockDividendResult",
    "data_id": '6472',
    "start_date": '2019-01-01',
    "token": token,  # 參考登入，獲取金鑰
}
data = requests.get(url, params=parameter)
data = data.json()
df = pd.DataFrame(data['data'])
print(df)`

**Desktop (please complete the following information):**[提供程式的執行環境]
 - OS: [e.g. iOS, windows] Windows
 - Browser [e.g. chrome, safari] Edge
 - Python Version [e.g. 3.6] 3.10
 - FinMind package Version [e.g. 1.4.5]

**Comment by linsamtw** [comment]
你好，以上比對櫃買中心資料，是一致的哦

![image](https://github.com/FinMind/FinMind/assets/20013414/9a8088ad-45a3-49a7-ab12-bebb75187e2b)

**Comment by yisenliu** [comment]
這檔股票的權息金額在2022年以後也有問題，與公開資訊觀測站不一致：
[https://api.finmindtrade.com/api/v4/data?dataset=TaiwanStockDividendResult&data_id=2886&start_date=2022-01-01&end_date=2024-06-17](url)
![image](https://github.com/FinMind/FinMind/assets/5609838/8c84d554-b712-470e-a72a-89d8d00e9a37)
![image](https://github.com/FinMind/FinMind/assets/5609838/4f58f82a-a34b-40dd-8b88-b1c480dad379)
![image](https://github.com/FinMind/FinMind/assets/5609838/7b6b76a4-b2e3-49f4-863a-b6fe7f31796a)

**Comment by linsamtw** [comment]
好的，我們檢查一下

**Comment by linsamtw** [comment]
已修復
![image](https://github.com/user-attachments/assets/a53d6205-d78b-49b6-85de-bc6bde7415fd)
