### ISSUE TITLE
似乎沒有當日的即時資料？

### ISSUE THREAD

**Issue by pahome** [FinMind/FinMind#32]
感謝大大開放這麼方便的API讓大家使用

在看到文件教學時試著操作以下部分取得今日5/8的股票資訊
```
form_data = {'dataset':'TaiwanStockPrice','stock_id':'2330','date':'2020-05-08'}
res = requests.post(url,verify = True,data = form_data)

temp = res.json()
data = pd.DataFrame(temp['data'])
data.head()
```

但是卻沒有跑出今日5/8的資料？ 請問是通常會延遲一天嗎

謝謝

**Comment by linsamtw** [comment]
已更新，通常是 1440左右更新，也就是下午2.30收盤後，更新

今天臨時有狀況，所以沒更新到，感謝提醒

lampahome <notifications@github.com> 於 2020年5月8日 週五 下午11:06寫道：
