### ISSUE TITLE
FinancialStatements 取出來都是空的

### ISSUE THREAD

**Issue by aicsfrankhsueh** [FinMind/FinMind#34]
url = "http://api.finmindtrade.com/api/v2/data"
    parameter = {
        "dataset": "FinancialStatements",
        "stock_id": id,
        "date": str(year) + '-01-01',
    }
    data = requests.get(url, params=parameter)
    data = data.json()
    data = pd.DataFrame(data['data'])
    print(data.head())

結果是
Empty DataFrame
Columns: []
Index: []
None

**Comment by linsamtw** [comment]
id 跟 year 你帶多少?

可以參考 [document](https://finmind.github.io/tutor/TaiwanMarket/Fundamental/#financialstatements)

**Comment by aicsfrankhsueh** [comment]
帶很多隻都一樣情況

**Comment by linsamtw** [comment]
修復中，晚點就會有了，感謝

**Comment by linsamtw** [comment]
有資料了，如果有想要的欄位，api 沒有提供，再跟我說
