### ISSUE TITLE
台灣股票清單不同index 內容是同樣的stock id

### ISSUE THREAD

**Issue by keyword1983** [FinMind/FinMind#36]
idx=17736 id=6552 type=twse industry_category=半導體類
Grab BS table: id=6552 type=twse

idx=17737 id=6552 type=twse industry_category=電子工業
Grab BS table: id=6552 type=twse

idx=17738 id=6558 type=twse industry_category=其他電子業
Grab BS table: id=6558 type=twse

idx=17739 id=6558 type=twse industry_category=其他電子類
Grab BS table: id=6558 type=twse

idx=17740 id=6558 type=twse industry_category=電子工業
Grab BS table: id=6558 type=twse

取到的表可以看到不同的index 卻是同樣的id

**Comment by Conjuror** [comment]
可以請問表是怎麼取的嗎？

**Comment by keyword1983** [comment]
1.
TaiwanStockInfo = Load.FinData(dataset = 'TaiwanStockInfo')
print(len(TaiwanStockInfo['stock_id']))

2.
url = "http://api.finmindtrade.com/api/v2/data"
#url = 'http://finmindapi.servebeer.com/api/data'
parameter = {
        "dataset": "TaiwanStockInfo",
}
data = requests.get(url, verify=True, params=parameter)
data = data.json()
TaiwanStockInfo = pd.DataFrame(data['data'])

我用這兩種方式都試過

接著 for
for i in range(0,len(TaiwanStockInfo['stock_id'])):
    id = str(TaiwanStockInfo['stock_id'][i])
    print("idx="+str(i),"id="+id, "type="+str(TaiwanStockInfo['type'][i]),"industry_category="+TaiwanStockInfo['industry_category'][i])

**Comment by linsamtw** [comment]
> idx=17736 id=6552 type=twse industry_category=半導體類
> Grab BS table: id=6552 type=twse
> 
> idx=17737 id=6552 type=twse industry_category=電子工業
> Grab BS table: id=6552 type=twse
> 
> idx=17738 id=6558 type=twse industry_category=其他電子業
> Grab BS table: id=6558 type=twse
> 
> idx=17739 id=6558 type=twse industry_category=其他電子類
> Grab BS table: id=6558 type=twse
> 
> idx=17740 id=6558 type=twse industry_category=電子工業
> Grab BS table: id=6558 type=twse
> 
> 取到的表可以看到不同的index 卻是同樣的id

你好，資料來源是證交所，因為這家公司，屬於兩種產業

https://www.twse.com.tw/zh/page/trading/exchange/FMSRFK.html

可以參考這個

我剛剛有重新更新 data 了，現在 api 會多回傳一個參數，date，代表更新時間

**Comment by linsamtw** [comment]
> 可以請問表是怎麼取的嗎？

你好，api 細節可以參考這份文件

https://finmind.github.io/tutor/TaiwanMarket/DataList/

**Comment by linsamtw** [comment]
我開了 
[![Gitter](https://badges.gitter.im/FinMindTW/community.svg)](https://gitter.im/FinMindTW/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

有問題歡迎在上面直接聯繫
