### ISSUE TITLE
買賣日報

### ISSUE THREAD

**Issue by PeterChenTW** [FinMind/FinMind#37]
看了一下好像沒有上市個股買賣日報的資料
請問會開發嗎？

謝謝
不好意思打擾

**Comment by linsamtw** [comment]
https://bsr.twse.com.tw/bshtm/

有破解，並且爬蟲，但是上面寫明

**此資料不得逕自散布或販售，
並請詳閱「使用條款」**

其他資料因為有在政府資料開放平台，因此才能開成 api 給 user 使用

**Comment by linsamtw** [comment]
https://finmind.github.io/tutor/TaiwanMarket/Chip/#taiwanstocktradingdailyreport-backersponsor
