### ISSUE TITLE
關於台灣期權交易明細表的文件敘述

### ISSUE THREAD

**Issue by penut85420** [FinMind/FinMind#38]
文件內容提到「由於資料量過大，只提供 date 當天 data」
不過試用了一下發現還是可以取得過去的資料，請問是文件內容誤植嗎?

**Comment by linsamtw** [comment]
應該是我表達不好，是只能取得一天的 date，也就是你 input 參數 date 那天的 data

**Comment by linsamtw** [comment]
我開了 
[![Gitter](https://badges.gitter.im/FinMindTW/community.svg)](https://gitter.im/FinMindTW/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

有問題歡迎在上面直接聯繫

**Comment by penut85420** [comment]
感謝回覆！
