### ISSUE TITLE
TaiwanStockPrice column "spread" looks weird

### ISSUE THREAD

**Issue by hvgmbdmg** [FinMind/FinMind#41]
<img width="431" alt="2020-06-06 133231" src="https://user-images.githubusercontent.com/17697079/83936876-551f5200-a7fa-11ea-847d-92fb89183fae.png">

原先我以為TaiwanStockPrice的spread欄位是指與前日收盤的差，但是沒想到現在重新download絕大多數的spread都被改為-1.0，請問spread到底代表什麼意義? 更令我困惑的是，有部分的spread依舊維持原有的data。

**Comment by hvgmbdmg** [comment]
<img width="440" alt="2020-06-06 133232" src="https://user-images.githubusercontent.com/17697079/83937045-e642f880-a7fb-11ea-9471-77e86bd76391.png">

此外，我發覺有部分的資料跟過往不一致，請問你們更換資料來源過嗎? 有確認過哪方比較可靠嗎?
以我提供的case，參考其他網站的結果似乎是舊資料較為可靠，但我無法確認這一點，因此提出討論。

**Comment by linsamtw** [comment]
謝謝，可以提供我股票代碼嗎？我回去查查看

Albert Shen <notifications@github.com>於 2020年6月6日 週六，下午1:48寫道：

**Comment by hvgmbdmg** [comment]
我認為是所有股票都有這個問題，好消息是看起來是特定日期。
股票的話，目前有1101, 1102, 1103, 1104, 1108, 1109, 1110, 1201, 1203 ...
2011-04-14, 2012-06-11 (很可能有更多，但是目前diff過於雜亂，比較難幫你追)

**Comment by linsamtw** [comment]
好，感謝，修復中

Albert Shen <notifications@github.com>於 2020年6月6日 週六，下午1:59寫道：

**Comment by hvgmbdmg** [comment]
補充一個個案，1203
2018-07-10 00:00:00,393,9979,-10000.0,-10000.0,-10000.0,-10000.0,0.0,7
其他的2018-07-10目前沒看到問題。
謝謝，麻煩你了。

**Comment by linsamtw** [comment]
正將所有爬蟲重新 run 一遍，預計今晚就會修正完畢

**Comment by hvgmbdmg** [comment]
不客氣，這麼好的Project當然希望他可以健康茁壯，很高興能為此盡一份心力。

**Comment by linsamtw** [comment]
已修復

**Comment by hvgmbdmg** [comment]
@linsamtw 
很抱歉再次打擾，但這個問題並未修復。
<img width="433" alt="2020-06-07 100319" src="https://user-images.githubusercontent.com/17697079/83958599-38405880-a8a6-11ea-94c5-b2fb5ad350a3.png">

上圖是1102，很明顯紅色的舊資料是更為合理的，而且這個狀況依舊出現在
2010-11-08, 2011-04-14

<img width="426" alt="2020-06-07 100320" src="https://user-images.githubusercontent.com/17697079/83958679-3cb94100-a8a7-11ea-8548-e37daaf118d4.png">

很顯然spread都是-1.0的狀況也依舊存在。
或許你們可以先專心重新爬某一隻股票，並拿以前的資料來做比較，確定沒問題再重新爬所有的。

**Comment by linsamtw** [comment]
sorry，正在修復

**Comment by linsamtw** [comment]
> 補充一個個案，1203
> 2018-07-10 00:00:00,393,9979,-10000.0,-10000.0,-10000.0,-10000.0,0.0,7
> 其他的2018-07-10目前沒看到問題。
> 謝謝，麻煩你了。

這個 case 修復了，變成 
2018-07-10 | 393 | 9979 | 0 | 0 | 0 | 0 | 0 | 7 | 1203
其中 0 代表無資料，有去證交所比對過

**Comment by linsamtw** [comment]
> @linsamtw
> 很抱歉再次打擾，但這個問題並未修復。
> <img alt="2020-06-07 100319" width="433" src="https://user-images.githubusercontent.com/17697079/83958599-38405880-a8a6-11ea-94c5-b2fb5ad350a3.png">
> 
> 上圖是1102，很明顯紅色的舊資料是更為合理的，而且這個狀況依舊出現在
> 2010-11-08, 2011-04-14
> 
> <img alt="2020-06-07 100320" width="426" src="https://user-images.githubusercontent.com/17697079/83958679-3cb94100-a8a7-11ea-8548-e37daaf118d4.png">
> 
> 很顯然spread都是-1.0的狀況也依舊存在。
> 或許你們可以先專心重新爬某一隻股票，並拿以前的資料來做比較，確定沒問題再重新爬所有的。

這兩個 case 檢查過，已修復

**Comment by hvgmbdmg** [comment]
> > 補充一個個案，1203
> > 2018-07-10 00:00:00,393,9979,-10000.0,-10000.0,-10000.0,-10000.0,0.0,7
> > 其他的2018-07-10目前沒看到問題。
> > 謝謝，麻煩你了。
> 
> 這個 case 修復了，變成
> 2018-07-10 | 393 | 9979 | 0 | 0 | 0 | 0 | 0 | 7 | 1203
> 其中 0 代表無資料，有去證交所比對過

Yup, 這部分確實修復了。
但是我在想這是否合理，因為看起來還是有交易達成，只是都是在同一個價位達成交易。
所以 2018-07-10 | 393 | 9979 | 25.35 | 25.35 | 25.35 | 25.35 | 0 | 7 | 1203 是否會更為合理一點?
當然這部分也可以選擇給download資料的人自己寫Adapter。
上述應該算是enhance，可以評估一下是否要做。

**Comment by hvgmbdmg** [comment]
> > @linsamtw
> > 很抱歉再次打擾，但這個問題並未修復。
> > <img alt="2020-06-07 100319" width="433" src="https://user-images.githubusercontent.com/17697079/83958599-38405880-a8a6-11ea-94c5-b2fb5ad350a3.png">
> > 上圖是1102，很明顯紅色的舊資料是更為合理的，而且這個狀況依舊出現在
> > 2010-11-08, 2011-04-14
> > <img alt="2020-06-07 100320" width="426" src="https://user-images.githubusercontent.com/17697079/83958679-3cb94100-a8a7-11ea-8548-e37daaf118d4.png">
> > 很顯然spread都是-1.0的狀況也依舊存在。
> > 或許你們可以先專心重新爬某一隻股票，並拿以前的資料來做比較，確定沒問題再重新爬所有的。
> 
> 這兩個 case 檢查過，已修復

spread的部分看起來是全部都修好了👍
資料不一致的還剩下2012-11-05這天

**Comment by linsamtw** [comment]
> 2012-11-05

修復了

**Comment by hvgmbdmg** [comment]
LGTM
Cheers!!
