### ISSUE TITLE
個股單日成交量資訊

### ISSUE THREAD

**Issue by frankShih** [FinMind/FinMind#44]
您好，

想請教一下，是否有提供單日成交量資訊?
還是這個值可以從其他支 API 回傳結果計算得出?

煩請提供指教

感謝

**Comment by linsamtw** [comment]
你是指大盤嗎? 還是個股?

https://finmind.github.io/tutor/TaiwanMarket/Technical/#taiwanstockprice

這有個股成交量

**Comment by frankShih** [comment]
感謝
