### ISSUE TITLE
請問API可以提供POST的嗎

### ISSUE THREAD

**Issue by mjtsai0224** [FinMind/FinMind#45]
很久以前API是POST的，後來以為壞了，最近才發現是換URL了，但只能用GET，我是寫JAVA的，大部的library的GET的interface沒辦法帶request body，滿困擾的，不然就只能用URL?dataset=TaiwanStockPrice&stock_id=2317&date=2018-06-01&end_date=2020-04-12

**Comment by linsamtw** [comment]
> 很久以前API是POST的，後來以為壞了，最近才發現是換URL了，但只能用GET，我是寫JAVA的，大部的library的GET的interface沒辦法帶request body，滿困擾的，不然就只能用URL?dataset=TaiwanStockPrice&stock_id=2317&date=2018-06-01&end_date=2020-04-12

你說的問題，

**只能用URL?dataset=TaiwanStockPrice&stock_id=2317&date=2018-06-01&end_date=2020-04-12**

應該可以在 request 上多包一層自己寫的 func，用 for loop dict 去把參數帶進去，

例如在 python 中的 dict 是這樣，

    parameter = {
        "dataset": "TaiwanStockPrice",
        "stock_id": "2330",
        "date": "2020-04-02",
        "end_date": "2020-04-12",
    }
    

那可以用 for loop，把所有的 key、value 跟 url 結合


    url = "http://api.finmindtrade.com/api/v3/data?"
    parameter = {
        "dataset": "TaiwanStockPrice",
        "stock_id": "2330",
        "date": "2020-04-02",
        "end_date": "2020-04-12",
    }
    parameter_string = ""
    for key, value in parameter.items():
        parameter_string += "&" + key + "=" + value

    url += parameter_string[1:]
    print(url)
    # http://api.finmindtrade.com/api/v3/data?dataset=TaiwanStockPrice&stock_id=2330&date=2020-04-02&end_date=2020-04-12


以下是我用 java 測試的結果
	

    package test;

    import java.io.BufferedReader;
    import java.io.IOException;
    import java.io.InputStreamReader;
    import java.net.HttpURLConnection;
    import java.net.URL;
    import java.util.HashMap;
    import java.util.Map;

    class request {
        public static void main(String[] args) throws IOException {
            String url = "http://api.finmindtrade.com/api/v3/data?";
            Map<String, Object> parameter = new HashMap<String, Object>();
            // dict
            parameter.put("dataset", "TaiwanStockPrice");
            parameter.put("stock_id", "2330");
            parameter.put("date", "2020-04-06");
            parameter.put("end_date", "2020-04-07");
            // send
            String resp = sendGET(url, parameter);
            System.out.println(resp);
            System.out.println("GET DONE");
        }

        private static String sendGET(String url, Map<String, Object> parameter) throws IOException {
            // loop dict
            String request_params_string = "";
            for (String key : parameter.keySet()) {
                String str = String.format("&%s=%s", key,parameter.get(key));  
                request_params_string += str;
            }
            request_params_string = request_params_string.substring(1, request_params_string.length());
            // url + request_params_string
            url += request_params_string;  
            System.out.println(url);

            URL obj = new URL(url);
            HttpURLConnection con = (HttpURLConnection) obj.openConnection();
            con.setRequestMethod("GET");
            BufferedReader in = new BufferedReader(new InputStreamReader(
                    con.getInputStream()));
            String inputLine;
            StringBuffer response = new StringBuffer();
            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
                }
            in.close();
            return response.toString();
        }
    }



#### output

	http://api.finmindtrade.com/api/v3/data?date=2020-04-06&end_date=2020-04-07&dataset=TaiwanStockPrice&stock_id=2330
    {"msg":"success","status":200,"data":[{"date":"2020-04-06","stock_id":"2330","Trading_Volume":59712754,"Trading_money":16324198154,"open":273.0,"max":275.5,"min":270.0,"close":275.5,"spread":4.0,"Trading_turnover":19971.0},{"date":"2020-04-07","stock_id":"2330","Trading_Volume":48887346,"Trading_money":13817936851,"open":283.5,"max":284.0,"min":280.5,"close":283.0,"spread":7.5,"Trading_turnover":24281.0}]}
    GET DONE


用法跟 python 蠻像的，

#### python 
	resp = requests.get(url, params)

#### java

	String resp = sendGET(url, parameter);
