### ISSUE TITLE
請問有 CNN fear and greed index 嗎？

### ISSUE THREAD

**Issue by conscientiousness** [FinMind/FinMind#46]
看文件應該是沒有
https://money.cnn.com/data/fear-and-greed/
拿來回測或當風險控管指標感覺蠻有趣的，希望有機會新增，感謝您

**Comment by machineCYC** [comment]
請問有相對應 fear & greed index 的 url 嗎?

如上提供的網頁好像都是圖，這目前比較難抓下來

**Comment by xuan-wang** [comment]
https://github.com/leejustin/fgi-tracker

**Comment by machineCYC** [comment]
@xuan-wang  url 是可以用的?

**Comment by xuan-wang** [comment]
> 
> 
> @xuan-wang url 是可以用的?

you can get the text info from source code of the officical page
![屏幕截图 2020-09-30 232726](https://user-images.githubusercontent.com/5609362/94706498-d89a1b80-0374-11eb-9fe6-da3c2441fca3.png)

**Comment by machineCYC** [comment]
> > @xuan-wang url 是可以用的?
> 
> you can get the text info from source code of the officical page
> ![屏幕截图 2020-09-30 232726](https://user-images.githubusercontent.com/5609362/94706498-d89a1b80-0374-11eb-9fe6-da3c2441fca3.png)

This does not have a history data, maybe have a source with history is better.

**Comment by xuan-wang** [comment]
> 
> 
> > > @xuan-wang url 是可以用的?
> > 
> > 
> > you can get the text info from source code of the officical page
> > ![屏幕截图 2020-09-30 232726](https://user-images.githubusercontent.com/5609362/94706498-d89a1b80-0374-11eb-9fe6-da3c2441fca3.png)
> 
> This does not have a history data, maybe have a source with history is better.

here, historical data https://github.com/hackingthemarkets/sentiment-fear-and-greed
in the datasets dir

**Comment by machineCYC** [comment]
thanks for this link, we will develop this data api asap.

**Comment by linsamtw** [comment]
目前已新增到資料庫，每天更新，但是 https://github.com/hackingthemarkets/sentiment-fear-and-greed 這裡提供的歷史資料，只到 2020-09-18，因此資料有斷層，2020-09-18 ~ 2020-11-12 這段時間並無資料，等對方下次更新歷史資料後，就會完整了，到時候再開放 api 提供使用

**Comment by xuan-wang** [comment]
https://indexvision.net/en/fear-and-greed/
here, another useful platform
note the algorithm of this FNG index is different from the one of CNN's index
record these data locally if necessary

**Comment by conscientiousness** [comment]
> https://indexvision.net/en/fear-and-greed/
> here, another useful platform
> note the algorithm of this FNG index is different from the one of CNN's index
> record these data locally if necessary

cool! Looks better than CNN's index, but need to backtest to find out, haha

**Comment by machineCYC** [comment]
> https://indexvision.net/en/fear-and-greed/
> here, another useful platform
> note the algorithm of this FNG index is different from the one of CNN's index
> record these data locally if necessary

we may consider that data source, thanks

**Comment by linsamtw** [comment]
由於 https://github.com/hackingthemarkets/sentiment-fear-and-greed 還沒更新，但有點久了，我還是先開放出 api，但是2020-09-18 ~ 2020-11-12 這段時間並無資料，如果有 user 願意提供的話，我再加進資料庫，不然就要等對方更新

**Comment by linsamtw** [comment]
@xuan-wang @conscientiousness 

https://finmind.github.io/tutor/Others/#cnnfeargreedindex

已新增 CnnFearGreedIndex
