### ISSUE TITLE
[台股] 資料正確性疑問

### ISSUE THREAD

**Issue by frankShih** [FinMind/FinMind#48]
您好，

我試著將資料撈下來看，發現 

1235 的 EPS (2017)，似乎和其他外部網站的數字對不上?

例如，
https://goodinfo.tw/StockInfo/StockDividendPolicy.asp?STOCK_ID=1235
https://mops.twse.com.tw/server-java/t164sb01?step=1&CO_ID=1235&SYEAR=2018&SSEASON=3&REPORT_ID=C

還請提供意見，感謝

**Comment by linsamtw** [comment]
![image](https://user-images.githubusercontent.com/20013414/87367992-05793680-c5af-11ea-8344-277f7411bdc5.png)

感謝提供 issus，
資料來源是，公開資訊觀測站，https://mops.twse.com.tw/mops/web/t164sb04
同時查詢 106、107 第二季，結果卻不同，原因是因為增資，

因為爬蟲，同一個頁面，會抓到兩年的資料，但因為增資，影響 eps 計算，
這週會修復，只抓當年的資料，避免因為增資，影響 eps 計算

**Comment by linsamtw** [comment]
已修復囉，麻煩再 check ，感謝

**Comment by frankShih** [comment]
您好，
1235 EPS 已確認無誤

另外想請教一下， 1101 在 2017/4/19~20 
成交量都是 0 貌似暫停交易，但資料上直接全給 0，這是有特殊用意嗎?
(只是問問，我自己濾掉，問題不大)

**Comment by linsamtw** [comment]
> 您好，
> 1235 EPS 已確認無誤
> 
> 另外想請教一下， 1101 在 2017/4/19~20
> 成交量都是 0 貌似暫停交易，但資料上直接全給 0，這是有特殊用意嗎?
> (只是問問，我自己濾掉，問題不大)

![image](https://user-images.githubusercontent.com/20013414/87865936-ab60e280-c9ad-11ea-9778-1f24b2ef2c7e.png)

沒特殊用意，主要是證交所也給 0，我希望資料盡可能跟證交所一致
