### ISSUE TITLE
請問 request 上限為何註冊登入了還是無法正確的的使用小時 1500 次呢?

### ISSUE THREAD

**Issue by seanmars** [FinMind/FinMind#49]
發生好幾次在有傳送帳號密碼的狀況下小時內才 request 不到 1500 就被拒絕的狀況。

**Comment by linsamtw** [comment]
> 發生好幾次在有傳送帳號密碼的狀況下小時內才 request 不到 1500 就被拒絕的狀況。

FinMind.TW@gmail.com

可以寄信給我你的帳號嗎?
我幫你查查 log

**Comment by linsamtw** [comment]
> 發生好幾次在有傳送帳號密碼的狀況下小時內才 request 不到 1500 就被拒絕的狀況。

麻煩再幫我試試看

**Comment by seanmars** [comment]
> > 發生好幾次在有傳送帳號密碼的狀況下小時內才 request 不到 1500 就被拒絕的狀況。
> 
> 麻煩再幫我試試看

目前測試正常
