### ISSUE TITLE
請問這兩天伺服器都做維修嗎？

### ISSUE THREAD

**Issue by pahome** [FinMind/FinMind#50]
as title

請問大概會關閉到啥時呢

謝謝

**Comment by linsamtw** [comment]
沒有關閉阿，你是連到哪個 url?

**Comment by linsamtw** [comment]
document

https://finmind.github.io/

**Comment by pahome** [comment]
我用這個耶

http://finmindapi.servebeer.com/api/v2/data?dataset=TaiwanStockPrice&stock_id=2408&date=2020-08-04

**Comment by linsamtw** [comment]
幫我換成這個
https://api.finmindtrade.com/api/v2/data

**Comment by pahome** [comment]
好的謝謝

剛好換api了嗎

**Comment by linsamtw** [comment]
其實本來網址都是通用的，文件也都是用新的網址，你應該是早期的 user

最近做改版，加上 ssl，然後把免費的網址拿掉，改用付費的，安全性也比較高

**Comment by pahome** [comment]
感謝大大的協助，百忙之中抽空為小弟解答
