### ISSUE TITLE
伺服器回應非常慢

### ISSUE THREAD

**Issue by seanmars** [FinMind/FinMind#51]
這兩天伺服器回應變得非常的慢，請問是不是伺服器有問題呀? 謝謝

**Comment by linsamtw** [comment]
好，我看看

**Comment by linsamtw** [comment]
現在有變快嗎?

速度是不是有時快有時慢?

**Comment by seanmars** [comment]
> 現在應該變快了吧?
> 
> 之前確實速度有變慢，因為雲端機器不足，資源會互搶，
> 
> 剛剛調整後，讓 api 的機器，只單純做 api service

感謝協助，順暢多了

**Comment by linsamtw** [comment]
> > 現在應該變快了吧?
> > 之前確實速度有變慢，因為雲端機器不足，資源會互搶，
> > 剛剛調整後，讓 api 的機器，只單純做 api service
> 
> 感謝協助，順暢多了

我剛剛看了一下 log，你是一次一次拿一支股票資訊對吧?

未來會開發新功能，一次拿所有股票的股價、三大法人等資訊，就不用一次次發 request 了

**Comment by seanmars** [comment]
> > > 現在應該變快了吧?
> > > 之前確實速度有變慢，因為雲端機器不足，資源會互搶，
> > > 剛剛調整後，讓 api 的機器，只單純做 api service
> > 
> > 
> > 感謝協助，順暢多了
> 
> 我剛剛看了一下 log，你是一次一次拿一支股票資訊對吧?
> 
> 未來會開發新功能，一次拿所有股票的股價、三大法人等資訊，就不用一次次發 request 了

對，太棒了! 這樣省時多了! 再次感謝!
