### ISSUE TITLE
請問這兩天也不提供服務嗎？

### ISSUE THREAD

**Issue by pahome** [FinMind/FinMind#55]
剛試著get data發現似乎都沒有資料傳回來了

請問這兩天有維修嗎？

謝謝

**Comment by linsamtw** [comment]
沒有進行維修，是哪個 data 沒資料呢?

**Comment by pahome** [comment]
我看了下url是
https://api.finmindtrade.com/api/v2/data?dataset=TaiwanStockPrice&stock_id=2408&date=2020-09-24

還是API更新了？

**Comment by linsamtw** [comment]
已修復，爬蟲出現 error 導致新 data 沒抓到

**Comment by pahome** [comment]
正常了 感謝
