### ISSUE TITLE
請問財務報表的更新時間

### ISSUE THREAD

**Issue by peterdu989** [FinMind/FinMind#58]
- 2020Q3的部分會在11月中下旬更新嗎? 如下網址
[https://mops.twse.com.tw/mops/web/t163sb04](https://mops.twse.com.tw/mops/web/t163sb04)
- 另外想請問台積電[官網](https://www.tsmc.com/chinese/investorRelations/quarterly_results.htm#2020Q3)有公布第三季財報，
如不想等公開資訊觀測站，有其他整合的資料源嗎?
謝謝

**Comment by linsamtw** [comment]
資料來源https://mops.twse.com.tw/mops/web/t163sb04

每天會從這抓取資料，只要有更新，就會有資料。

如果要從每家公司官網，都抓財報，這工有點多。

**Comment by peterdu989** [comment]
感謝回覆!
