### ISSUE TITLE
[API 異常] 台股 籌碼面 TaiwanStockHoldingSharesPer

### ISSUE THREAD

**Issue by frankShih** [FinMind/FinMind#60]
您好

近期抓取台股 "籌碼面" 相關資料時，經常出現 500 status code
以 TaiwanStockHoldingSharesPer 為例:
1256, 1592, 2546, 5284 都有這樣的狀況 
(目前只發現這幾個，前陣子測試 TaiwanStockMarginPurchaseShortSale 也有類似狀況)

個人測試時發現，若時間區間拉短一點，則會正常返回資料
全抓的話則會出狀況
![image](https://user-images.githubusercontent.com/8334979/98750551-38b2c180-23f9-11eb-8f0e-85fbc73d969e.png)

想請教一下，
是 API 服務有異常狀況，還是 API 服務政策有更新之類的
抑或是我忽略了甚麼 API 呼叫的基本規範?

煩請提供協助
感謝您

**Comment by frankShih** [comment]
順便報個 TYPO
![image](https://user-images.githubusercontent.com/8334979/98752145-87158f80-23fc-11eb-87fe-f902dd54e877.png)

**Comment by linsamtw** [comment]
> 您好
> 
> 近期抓取台股 "籌碼面" 相關資料時，經常出現 500 status code
> 以 TaiwanStockHoldingSharesPer 為例:
> 1256, 1592, 2546, 5284 都有這樣的狀況
> (目前只發現這幾個，前陣子測試 TaiwanStockMarginPurchaseShortSale 也有類似狀況)
> 
> 個人測試時發現，若時間區間拉短一點，則會正常返回資料
> 全抓的話則會出狀況
> ![image](https://user-images.githubusercontent.com/8334979/98750551-38b2c180-23f9-11eb-8f0e-85fbc73d969e.png)
> 
> 想請教一下，
> 是 API 服務有異常狀況，還是 API 服務政策有更新之類的
> 抑或是我忽略了甚麼 API 呼叫的基本規範?
> 
> 煩請提供協助
> 感謝您
TaiwanStockHoldingSharesPer 我剛剛看 1256，已修復，其他應該沒問題了，主要是因為遇到 NA，資料型態轉不過來

TaiwanStockMarginPurchaseShortSale 也一併修正了，麻煩再幫我檢查看看，感謝

**Comment by linsamtw** [comment]
> 順便報個 TYPO
> ![image](https://user-images.githubusercontent.com/8334979/98752145-87158f80-23fc-11eb-87fe-f902dd54e877.png)

已修復
