### ISSUE TITLE
請問TaiwanStockPER特定日期取不到資料

### ISSUE THREAD

**Issue by peterdu989** [FinMind/FinMind#68]
```R
library(httr)
library(data.table)
library(dplyr)
url = 'https://api.finmindtrade.com/api/v3/data'
response = httr::GET(url = url,
                     query = list(
                             dataset="TaiwanStockPER",
                             stock_id= "2834",
                             date= "2010-01-01"
                     )
)
```
![image](https://user-images.githubusercontent.com/10435392/103001009-1f0fa880-4567-11eb-8559-136081bfd10c.png)

日期改到2011-01-01便可拿到資料，有辦法知道各股的最早日期嗎?
![image](https://user-images.githubusercontent.com/10435392/103001107-4fefdd80-4567-11eb-896a-fa5dc95a0a66.png)

謝謝!

**Comment by machineCYC** [comment]
@peterdu989 目前應該是沒有這樣的資訊! 可能在未來會提供!

**Comment by peterdu989** [comment]
還是有辦法送某個日期，傳回最早日期嗎？

**Comment by linsamtw** [comment]
已修復，date= "2010-01-01"，現在 ok 了
