### ISSUE TITLE
TaiwanStockPriceBidAsk 回應的data為空

### ISSUE THREAD

**Issue by htcHIMA** [FinMind/FinMind#77]
TaiwanStockPriceBidAsk 五檔回應的data為空，再麻煩確認一下，感恩~!!

**Comment by linsamtw** [comment]
目前已收盤，所以不回傳 data，盤中才會回傳 data

**Comment by htcHIMA** [comment]
感謝回覆，但我記得之前是收盤之後也會有整天的五檔歷史資料耶

**Comment by linsamtw** [comment]
對，但資料量過大，DB 負荷不了，正在優化 DB，未來會再提供歷史 bidask

**Comment by htcHIMA** [comment]
了解，還是說能僅限提供前一天或前一周的資料呢? 這樣需要儲存的資料量會不會小一點呢?

**Comment by linsamtw** [comment]
這周日凌晨，會去優化 DB，如果弄好的話，之後就可以拿 bidask 了

**Comment by htcHIMA** [comment]
感謝  辛苦了

**Comment by linsamtw** [comment]
![image](https://user-images.githubusercontent.com/20013414/105621473-a7bd8500-5e42-11eb-962e-0f8f772a2f9b.png)

修好了，剛剛在雲端測，約 40 秒

**Comment by htcHIMA** [comment]
感謝!!!辛苦了!!
另外線上API的v3 dataset 選單裡面好像沒有 TaiwanStockPriceMinuteBidAsk 這個選項可以直接選(?)
https://api.finmindtrade.com/docs#/default/data_api_v3_data_get

**Comment by linsamtw** [comment]
![image](https://user-images.githubusercontent.com/20013414/105685237-ce59e980-5f30-11eb-831a-c26b1d0fec52.png)

我們目前有 web 了，直接用 web 比較方便

https://finmindtrade.com/

**Comment by htcHIMA** [comment]
OK 感謝!!

**Comment by htcHIMA** [comment]
現在是不是又沒五檔資料了XD
![image](https://user-images.githubusercontent.com/10808596/105695820-7c6b9080-5f3d-11eb-9b84-fe6dc6b043a7.png)

**Comment by linsamtw** [comment]
試試看歷史的，因為收盤了

**Comment by linsamtw** [comment]
![Uploading 5FCC889E-A525-42EB-9F35-E3F5AB5A28A9.png…]()

**Comment by htcHIMA** [comment]
有了  感謝!!
