### ISSUE TITLE
減資

### ISSUE THREAD

**Issue by linsamtw** [FinMind/FinMind#95]
https://www.twse.com.tw/zh/page/trading/exchange/TWTAUU.html

https://www.tpex.org.tw/web/stock/exright/revivt/revivt.php?l=zh-tw

**Comment by linsamtw** [comment]
TaiwanStockCapitalReductionReferencePrice

**Comment by machineCYC** [comment]
already have the data(TaiwanStockCapitalReductionReferencePrice dataset) for this issue
